# Generated by Django 5.0.14 on 2025-08-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_teacher_serial_no_alter_teacher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
