# Generated by Django 5.0.14 on 2025-08-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_facultyteacher_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyteacher',
            name='serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
